/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as BantuanRouteImport } from './routes/bantuan'
import { Route as CmsRouteImport } from './routes/cms'
import { Route as FiturRouteImport } from './routes/fitur'
import { Route as HargaRouteImport } from './routes/harga'
import { Route as IntegrasiRouteImport } from './routes/integrasi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCmsRouteImport } from './routes/app/cms'
import { Route as AppCustomersRouteImport } from './routes/app/customers'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppExpensesRouteImport } from './routes/app/expenses'
import { Route as AppKitchenRouteImport } from './routes/app/kitchen'
import { Route as AppPosRouteImport } from './routes/app/pos'
import { Route as AppProductsRouteImport } from './routes/app/products'
import { Route as AppSalesRouteImport } from './routes/app/sales'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppShiftsRouteImport } from './routes/app/shifts'
import { Route as AppSuperadminRouteImport } from './routes/app/superadmin'
import { Route as AppUsersRouteImport } from './routes/app/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BantuanRoute = BantuanRouteImport.update({
  id: '/bantuan',
  path: '/bantuan',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const FiturRoute = FiturRouteImport.update({
  id: '/fitur',
  path: '/fitur',
  getParentRoute: () => rootRouteImport,
} as any)
const HargaRoute = HargaRouteImport.update({
  id: '/harga',
  path: '/harga',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrasiRoute = IntegrasiRouteImport.update({
  id: '/integrasi',
  path: '/integrasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCmsRoute = AppCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppKitchenRoute = AppKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperadminRoute = AppSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/bantuan': typeof BantuanRoute
  '/cms': typeof CmsRoute
  '/fitur': typeof FiturRoute
  '/harga': typeof HargaRoute
  '/integrasi': typeof IntegrasiRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/superadmin': typeof SuperadminRoute
  '/app/cms': typeof AppCmsRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/kitchen': typeof AppKitchenRoute
  '/app/pos': typeof AppPosRoute
  '/app/products': typeof AppProductsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/superadmin': typeof AppSuperadminRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bantuan': typeof BantuanRoute
  '/cms': typeof CmsRoute
  '/fitur': typeof FiturRoute
  '/harga': typeof HargaRoute
  '/integrasi': typeof IntegrasiRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/superadmin': typeof SuperadminRoute
  '/app/cms': typeof AppCmsRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/kitchen': typeof AppKitchenRoute
  '/app/pos': typeof AppPosRoute
  '/app/products': typeof AppProductsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/superadmin': typeof AppSuperadminRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/bantuan': typeof BantuanRoute
  '/cms': typeof CmsRoute
  '/fitur': typeof FiturRoute
  '/harga': typeof HargaRoute
  '/integrasi': typeof IntegrasiRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/superadmin': typeof SuperadminRoute
  '/app/cms': typeof AppCmsRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/kitchen': typeof AppKitchenRoute
  '/app/pos': typeof AppPosRoute
  '/app/products': typeof AppProductsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/superadmin': typeof AppSuperadminRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/bantuan'
    | '/cms'
    | '/fitur'
    | '/harga'
    | '/integrasi'
    | '/login'
    | '/register'
    | '/superadmin'
    | '/app/cms'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/expenses'
    | '/app/kitchen'
    | '/app/pos'
    | '/app/products'
    | '/app/sales'
    | '/app/settings'
    | '/app/shifts'
    | '/app/superadmin'
    | '/app/users'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bantuan'
    | '/cms'
    | '/fitur'
    | '/harga'
    | '/integrasi'
    | '/login'
    | '/register'
    | '/superadmin'
    | '/app/cms'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/expenses'
    | '/app/kitchen'
    | '/app/pos'
    | '/app/products'
    | '/app/sales'
    | '/app/settings'
    | '/app/shifts'
    | '/app/superadmin'
    | '/app/users'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/bantuan'
    | '/cms'
    | '/fitur'
    | '/harga'
    | '/integrasi'
    | '/login'
    | '/register'
    | '/superadmin'
    | '/app/cms'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/expenses'
    | '/app/kitchen'
    | '/app/pos'
    | '/app/products'
    | '/app/sales'
    | '/app/settings'
    | '/app/shifts'
    | '/app/superadmin'
    | '/app/users'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BantuanRoute: typeof BantuanRoute
  CmsRoute: typeof CmsRoute
  FiturRoute: typeof FiturRoute
  HargaRoute: typeof HargaRoute
  IntegrasiRoute: typeof IntegrasiRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SuperadminRoute: typeof SuperadminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bantuan': {
      id: '/bantuan'
      path: '/bantuan'
      fullPath: '/bantuan'
      preLoaderRoute: typeof BantuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitur': {
      id: '/fitur'
      path: '/fitur'
      fullPath: '/fitur'
      preLoaderRoute: typeof FiturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harga': {
      id: '/harga'
      path: '/harga'
      fullPath: '/harga'
      preLoaderRoute: typeof HargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrasi': {
      id: '/integrasi'
      path: '/integrasi'
      fullPath: '/integrasi'
      preLoaderRoute: typeof IntegrasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cms': {
      id: '/app/cms'
      path: '/cms'
      fullPath: '/app/cms'
      preLoaderRoute: typeof AppCmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kitchen': {
      id: '/app/kitchen'
      path: '/kitchen'
      fullPath: '/app/kitchen'
      preLoaderRoute: typeof AppKitchenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shifts': {
      id: '/app/shifts'
      path: '/shifts'
      fullPath: '/app/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/superadmin': {
      id: '/app/superadmin'
      path: '/superadmin'
      fullPath: '/app/superadmin'
      preLoaderRoute: typeof AppSuperadminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCmsRoute: typeof AppCmsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppKitchenRoute: typeof AppKitchenRoute
  AppPosRoute: typeof AppPosRoute
  AppProductsRoute: typeof AppProductsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShiftsRoute: typeof AppShiftsRoute
  AppSuperadminRoute: typeof AppSuperadminRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCmsRoute: AppCmsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppKitchenRoute: AppKitchenRoute,
  AppPosRoute: AppPosRoute,
  AppProductsRoute: AppProductsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShiftsRoute: AppShiftsRoute,
  AppSuperadminRoute: AppSuperadminRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BantuanRoute: BantuanRoute,
  CmsRoute: CmsRoute,
  FiturRoute: FiturRoute,
  HargaRoute: HargaRoute,
  IntegrasiRoute: IntegrasiRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SuperadminRoute: SuperadminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
